//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csdeployer._Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("csdeployer._Resource.HtmlResources", typeof(HtmlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html {
        ///    color: #1E1E1E;
        ///    Font: 12px &quot;Segoe UI&quot;;
        ///}
        ///
        ///hr {
        ///    border: 0;
        ///    height: 1px;
        ///    background: #647687 no-repeat scroll center;
        ///    width: 70%;
        ///}
        ///
        ///a {
        ///    color: #1580B3;
        ///    text-decoration: underline;
        ///}
        ///
        ///.linkSeparator {
        ///    color: #093850;
        ///}
        ///
        ///pre {
        ///    background-color: #FAFAFA;
        ///    Font: 12px &quot;Consolas&quot;;
        ///}
        ///
        ///code {
        ///    background-color: #FAFAFA;
        ///    padding-left: 5px;
        ///    padding-right: 5px;
        ///    Font: 11px &quot;Consolas&quot;;
        ///}
        ///
        ///table {
        ///    Font: 12px &quot;Segoe UI&quot;;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StyleSheet {
            get {
                return ResourceManager.GetString("StyleSheet", resourceCulture);
            }
        }
    }
}
